### ISSUE TITLE
OTGC app crashes when installed on ubuntu 16.04

### ISSUE THREAD

**Issue by payalgaikwad42** [openconnectivityfoundation/development-support#3]
Hi, 
I have OTGC app downloaded and installed on my ubuntu 16.04 from this link:
https://github.com/openconnectivityfoundation/development-support/tree/master/otgc#install-otgc-on-linux-x86-debian

But when I open the app it crashed immediately. does not show any window. 

Can someone help me to  install this app on my pc?

**Comment by cstevens** [comment]
I have not seen this before. I have had it crash when trying to control IoTivity-lite servers, but that was after a successful installation. I'll see if I can reproduce it. Also, you should know that we are creating a new, more stable version of OTGC that should be done in August. This version is based on IoTivity-lite which fixes some known issues in IoTivity. If you are not in a hurry, you may just want to wait for this.

**Comment by OICAdmin** [comment]
Hi,
This could happen if there a dependency conflict. Please un-install the OTGC. You can do so with the following command:
$ sudo dpkg –r otgc
Next re-install manually without using the shell script just to make sure all steps have succeeded assuming you have admin rights over this Ubuntu machine.
The OTGC application has the following dependencies, which must be installed
previously or the installation is not possible:

·        openjdk-8-jdk.

·        openjfx.
These dependencies can be installed using the following command:
$ sudo apt-get install <package>
where <package> is the name of the package to install.

Next, change to the directory where the OTGC Debian package has been downloaded using the console.
To install the OTGC application, execute the following command, which requires root privileges:
$ sudo dpkg -i otgc-<version>.deb
where <version> is the target version of the package downloaded (e.g. 1.3.0).

Once the installation process has finished, an icon of the OTGC application appears on the menu.
Thanks,
OCF Development support

**Comment by ravindra-gaikawad** [comment]
@OICAdmin 
I did same way, as you mentioned. still it crashes.

**Comment by ravindra-gaikawad** [comment]
@cstevens @OICAdmin 
I launched app as mentioned [Here](https://github.com/openconnectivityfoundation/development-support/blob/master/otgc/README.md#launch-the-otgc-on-linux-x86-debian)

Crash Logs:

```
2019-07-23 19:27:37 WARN  SqlExceptionHelper:137 - SQL Error: -104, SQLState: 23505
2019-07-23 19:27:37 ERROR SqlExceptionHelper:142 - integrity constraint violation: unique constraint or index violation; SYS_PK_10116 table: DEVICES
2019-07-23 19:27:37 ERROR ExceptionMapperStandardImpl:39 - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2019-07-23 19:27:37 WARN  SqlExceptionHelper:137 - SQL Error: -104, SQLState: 23505
2019-07-23 19:27:37 ERROR SqlExceptionHelper:142 - integrity constraint violation: unique constraint or index violation; SYS_PK_10116 table: DEVICES
2019-07-23 19:27:37 ERROR ExceptionMapperStandardImpl:39 - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
Exception in thread "Thread-7" #
javax.persistence.RollbackException: Error while committing the transaction2019-07-23 19:27:37 WARN  SqlExceptionHelper:137 - SQL Error: -104, SQLState: 23505

	at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:77)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
	at org.openconnectivity.otgc.common.data.persistence.DatabaseManager.commit(DatabaseManager.java:57)
	at org.openconnectivity.otgc.common.data.persistence.DatabaseManager.insertOrUpdate(DatabaseManager.java:67)
	at org.openconnectivity.otgc.common.data.persistence.dao.DeviceDao.insert(DeviceDao.java:73)
	at org.openconnectivity.otgc.common.data.repository.IotivityRepository$1.onResourcesFound(IotivityRepository.java:214)
2019-07-23 19:27:37 ERROR SqlExceptionHelper:142 - integrity constraint violation: unique constraint or index violation; SYS_PK_10116 table: DEVICES
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:149)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157)
	at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:61)
	... 5 more
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3167)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3682)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:90)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:478)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:356)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
2019-07-23 19:27:37 ERROR ExceptionMapperStandardImpl:39 - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=11956, tid=0x00007f149e4fc700
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b03) (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000000000
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr/share/otgc/hs_err_pid11956.log
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1454)
[thread 139726551508736 also had an error]
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:511)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3283)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2479)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:473)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:178)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:39)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:271)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:98)
	... 4 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SYS_PK_10116 table: DEVICES
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
Hibernate: select deviceenti0_.deviceid as deviceid1_0_, deviceenti0_.name as name2_0_ from DEVICES deviceenti0_ where deviceid=?
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	... 20 more
Caused by: org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; SYS_PK_10116 table: DEVICES
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Constraint.getException(Unknown Source)
	at org.hsqldb.index.IndexAVLMemory.insert(Unknown Source)
	at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
	at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
	at org.hsqldb.Session.addInsertAction(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 23 more
Hibernate: select hosts0_.id as id1_1_0_, hosts0_.host as host2_1_0_ from HOSTS hosts0_ where hosts0_.id=?
[thread 139726504826624 also had an error]
Hibernate: delete from HOSTS where id=?
Hibernate: insert into HOSTS (id, host) values (?, ?)
Hibernate: insert into HOSTS (id, host) values (?, ?)
[thread 139726540494592 also had an error]
[thread 139726513219328 also had an error]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
./otgc.sh: line 6: 11956 Aborted                 (core dumped) java -jar /usr/lib/otgc/otgc-1.3.0-jfx.jar
```
